# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
defaults = np.seterr(all="ignore")


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [14]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [5]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)


2024-11-14
2024-11-15
2024-11-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [6]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [7]:
A = np.arange(1,3)
B = np.arange(3,5) 
print(B)


[3 4]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [8]:
c = np.random.randint(1,10,(3,3))
c

array([[6, 6, 5],
       [9, 6, 9],
       [9, 1, 1]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [9]:
l = np.zeros((5,5))
l

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:



def integer_generator():
    for i in range(10):
        yield i

gen = integer_generator()
array = np.fromiter(gen, dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [12]:

k= np.linspace(0,1,10)
k


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
s= np.random.random(10)
s

array([0.42884729, 0.05340444, 0.95035652, 0.94129026, 0.28030548,
       0.33636854, 0.38007516, 0.06985119, 0.410184  , 0.17223426])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [14]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:


R = np.random.randint(0,10,(3,3))
R

array([[7, 4, 3],
       [8, 3, 1],
       [7, 4, 7]])

#### 43. Make an array immutable (read-only) (★★☆)

In [17]:


array = np.array([1, 2, 3, 4, 5])


array.setflags(write=False)


try:
    array[0] = 10  
except ValueError as e:
    print("Error:", e)


print("Read-only array:", array)


Error: assignment destination is read-only
Read-only array: [1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [12]:
import numpy as np

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)  # Random values between 0 and 1

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)  # Radius
theta = np.arctan2(y, x)   # Angle in radians

# Combine radius and angle into a new array
polar_coords = np.column_stack((r, theta))

print("Cartesian Coordinates:\n", cartesian_coords)
print("\nPolar Coordinates (r, theta):\n", polar_coords)


Cartesian Coordinates:
 [[0.46516816 0.78292835]
 [0.47860703 0.83446552]
 [0.36091874 0.84707635]
 [0.39781078 0.86310013]
 [0.39435743 0.98711352]
 [0.96123285 0.97104201]
 [0.77994071 0.89732417]
 [0.74553026 0.96299602]
 [0.64079194 0.34217061]
 [0.52038093 0.7432384 ]]

Polar Coordinates (r, theta):
 [[0.91069107 1.03469763]
 [0.96197578 1.05005305]
 [0.92076092 1.16801481]
 [0.95036585 1.13890744]
 [1.06297266 1.19071618]
 [1.36634227 0.7904746 ]
 [1.1889063  0.85526929]
 [1.21785742 0.91200006]
 [0.72642621 0.4904613 ]
 [0.90730349 0.95996738]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
N= np.random.random(10)
N

array([0.1409399 , 0.36541144, 0.70269619, 0.04384187, 0.18800748,
       0.95091082, 0.55015762, 0.78630938, 0.26576036, 0.01085259])