# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
j = np.zeros((3,3))
j

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.pad(j,pad_width=1,mode="constant",constant_values=1)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [4]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
z = np.diag([1, 2, 3, 4, 5])
z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [6]:
x = np.zeros((8,8))

x[1::2,::2] = 1

x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [7]:
np.unravel_index(100,(6,7,8))


(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
list_0_1 = np.array([ [ 0, 1], [ 1, 0] ])
checkerboard = np.tile(list_0_1, ( 8//2, 8//2)) 
checkerboard


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [9]:
import random
l = np.random.random((5,5))
l


array([[0.58224239, 0.77121236, 0.03174918, 0.38948896, 0.35591377],
       [0.52895208, 0.17553935, 0.94356331, 0.35528707, 0.86589932],
       [0.36852725, 0.34014812, 0.37298053, 0.62241265, 0.95490076],
       [0.85102274, 0.37266863, 0.50366643, 0.24286083, 0.76392673],
       [0.15143254, 0.22939195, 0.93754698, 0.51719986, 0.25579743]])

In [11]:
lmax, lmin = l.max(), l.min()
l = (l - lmin)/(lmax - lmin)
l


array([[0.59631942, 0.80102033, 0.        , 0.38752009, 0.35114991],
       [0.53859292, 0.15576009, 0.98771875, 0.35047104, 0.90358958],
       [0.36481341, 0.33407183, 0.36963741, 0.63983368, 1.        ],
       [0.88747458, 0.36929954, 0.51120235, 0.2286858 , 0.7931282 ],
       [0.12964649, 0.21409568, 0.9812016 , 0.52586237, 0.24269931]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [12]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
z = np.random.randint(1,10,(5,3))
z


array([[3, 2, 7],
       [9, 1, 3],
       [5, 8, 2],
       [7, 6, 6],
       [1, 4, 1]])

In [14]:
b = np.random.randint(1,10,(3,2))
b


array([[7, 5],
       [5, 8],
       [4, 5]])

In [15]:

np.dot(z,b)

array([[ 59,  66],
       [ 80,  68],
       [ 83,  99],
       [103, 113],
       [ 31,  42]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
t = np.arange(0,10)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
t[(3 < t) & (t < 8)] *= -1
t

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
9

9
10


9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z = np.arange(5)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([0., 1., 2., 3., 4.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/ls/fkq9d5mn7xn8l2ppz91475r40000gn/T/ipykernel_47481/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/ls/fkq9d5mn7xn8l2ppz91475r40000gn/T/ipykernel_47481/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/ls/fkq9d5mn7xn8l2ppz91475r40000gn/T/ipykernel_47481/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [23]:
v = np.random.uniform(-10,+10,10)
v


array([-9.59806298, -8.74604668, -1.98693142, -6.82193648, -7.89076914,
        8.98258896,  1.93173917, -3.26157671,  2.54090649,  5.7554892 ])

In [24]:
np.copysign(np.ceil(np.abs(v)), v)

array([-10.,  -9.,  -2.,  -7.,  -8.,   9.,   2.,  -4.,   3.,   6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [25]:
k = np.array([2,3,9,45,32,5,67])
h= np.array([45,23,4,12,67,2])
np.intersect1d(k,h)


array([ 2, 45, 67])