# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.1.2


#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
x = np.zeros(10)
x


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

x.nbytes

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:

y = np.zeros(10)
y[4] = 1
y


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
indices = np.nonzero([1,2,0,0,4,0])
indices

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
ran = np.random.random(3*3*3)
ran

array([0.76780995, 0.25899526, 0.29882665, 0.22421262, 0.80550444,
       0.91359287, 0.7961877 , 0.40480239, 0.34861229, 0.21726992,
       0.86654093, 0.23845821, 0.04905666, 0.73378998, 0.45839726,
       0.15784308, 0.3237122 , 0.02511886, 0.72337953, 0.0685993 ,
       0.27720277, 0.9550823 , 0.84640475, 0.36883858, 0.79164279,
       0.93631301, 0.8194012 ])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
y = np.random.random(10*100)
y_min = y.min()
y_max = y.max()

In [14]:
y_min

np.float64(0.0009521729045710581)

In [15]:

y_max

np.float64(0.99805551134288)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
z = np.random.random(30)


In [23]:
z

array([0.14328097, 0.26450623, 0.87248903, 0.99979908, 0.94983695,
       0.3739726 , 0.20041609, 0.68982551, 0.73843885, 0.78521269,
       0.043127  , 0.68212741, 0.6502902 , 0.41610915, 0.16294461,
       0.90544383, 0.95361426, 0.06238425, 0.14337341, 0.68296585,
       0.66797831, 0.0042225 , 0.79938557, 0.86807396, 0.50593412,
       0.1794038 , 0.7890213 , 0.53360918, 0.2433564 , 0.83925792])

In [24]:
z_mean = z.mean()
z_mean

np.float64(0.5383467003850337)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
z = np.arange(0,9).reshape(3,3)
z


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])